import * as yup from 'yup';

export const PersoanlLoanValidation = yup.object().shape({
    fname: yup.string().required("required field"),
    // mname: yup.string().notRequired("First Name is required"),
    lname: yup.string().required("required field"),
    email: yup.string().email("Invalid Email").required("required field"),
    phone: yup.string().required("Phone is required").matches(/^\d{10}$/, 'Phone number must be exactly 10 digits'),
    alternate_number: yup.string().required(" is required").matches(/^\d{10}$/, 'Phone number must be exactly 10 digits'),
    dob: yup.string().required("required field"),
    gender: yup.string().required("required field"),
    marital_status: yup.string().required("required field"),
    spouse_name: yup.string(),
    father_name: yup.string().required("required field"),
    mother_name: yup.string().required("required field"),
    house_name: yup.string().required("required field"),
    street_name: yup.string().required("required field"),
    city_name: yup.string().required("required field"),
    landmark: yup.string().required("required field"),
    district: yup.string().required("required field"),
    state: yup.string().required("required field"),
    pincode: yup.string().required("required field"),

    present_house_name: yup.string().required("required field"),
    present_street_name: yup.string().required("required field"),
    present_city_name: yup.string().required("required field"),
    present_landmark: yup.string().required("required field"),
    present_district: yup.string().required("required field"),
    present_state: yup.string().required("required field"),
    present_pincode: yup.string("Please Enter Number only").required("required field"),

    co_name: yup.string().required("required field"),
    co_date_of_birth: yup.string().required("required field"),
    occupation: yup.string().required("required field"),
    co_relation: yup.string().required("required field"),
    // job details
    salary_slip: yup.string().required("required field"),
    form16: yup.string().required("required field"),
    job_experience: yup.string().required("required field"),
    designation: yup.string().required("required field"),
    current_salary: yup.string().required("required field"),
    company_name: yup.string().required("required field"),
    current_job_experience: yup.string().required("required field"),
    office_building_name: yup.string().required("required field"),
    office_street_name: yup.string().required("required field"),
    office_city_name: yup.string().required("required field"),
    office_landmark: yup.string().required("required field"),
    office_district: yup.string().required("required field"),
    office_state: yup.string().required("required field"),
    office_pincode: yup.string().required("required field"),

    // Documents
    // adhar_front: yup.mixed().required("Aadhaar front image is Required"),
    // adhar_back: yup.mixed().required("Aadhaar Back image is required"),
    // pancard: yup.mixed().required("Pan Card is required"),
    // applicant_photo: yup.mixed().required("Applicant is required"),
    // address_proof: yup.mixed().required("Address Proof is required"),
    // first_month_salary: yup.mixed().required("First Month Salary is required"),
    // second_month_salary: yup.mixed().required("Second Month Salary is required"),
    // third_month_salary: yup.mixed().required("Third Month Salary is required"),
    // itr1: yup.string().required("ITR-1 is required"),
    // itr2: yup.string().required("ITR-2 is required"),

    // // other1:yup.string().required(""),
    // // other2:yup.string().required(""),
    // // other3:yup.string().required(""),
    // co_adhar_front:yup.string().required("Co-Applicant Aadhar is required"),
    // co_adhar_back:yup.string().required("Co-Applicant Aadhar is required"),
    // co_pancard:yup.string().required("Co-Applicant Pan Card is required"),
    // co_applicant_photo:yup.string().required("Co-Applicant Photo is required"),

})
export const BusinessLoanValidation = yup.object().shape({
    fname: yup.string().required("Required field"),
    // mname: yup.string().notRequired("First Name is required"),
    lname: yup.string().required("Required field"),
    email: yup.string().email("Invalid Email").required("Required field"),
    phone: yup.string().required("Required field").matches(/^\d{10}$/, 'Phone number must be exactly 10 digits'),
    alternate_number: yup.string().required(" Required field").matches(/^\d{10}$/, 'Phone number must be exactly 10 digits'),
    dob: yup.string().required("Required field"),
    gender: yup.string().required("Required field"),
    marital_status: yup.string().required("Required field"),
    spouse_name: yup.string(),
    father_name: yup.string().required("Required field"),
    mother_name: yup.string().required("Required field"),
    house_name: yup.string().required("Required field"),
    street_name: yup.string().required("Required field"),
    city_name: yup.string().required("Required field"),
    landmark: yup.string().required("Required field"),
    district: yup.string().required("Required field"),
    state: yup.string().required("Required field"),
    pincode: yup.string().required("Required field"),
    present_house_name: yup.string().required("Required field"),
    present_street_name: yup.string().required("Required fields"),
    present_city_name: yup.string().required("Required fields"),
    present_landmark: yup.string().required("Required fields"),
    present_district: yup.string().required("Required fields"),
    present_state: yup.string().required("Required fields"),
    present_pincode: yup.string().required("Required fields"),
    //bank_details
    // bank_name:yup.string().required("Required field"),
    // account_type:yup.string().required("Required field"),
    //co_applicant
    co_name: yup.string().required("Required field"),
    co_date_of_birth: yup.string().required("Required field"),
    occupation: yup.string().required("Required field"),
    co_relation: yup.string().required("Required field"),
    // business details
    // loan_purpose: yup.string().required("Required fields"),
    // company_name: yup.string().required("Required fields"),
    // business_register_year:yup.string().required("Required fields"),
    // registration_documents: yup.string().required("Required fields"),
    // business_turnover: yup.string().required("Required fields"),
    // file_itr: yup.string().required("Required fields"),
    // property_mortgage: yup.string().required("Required fields"),
    // property_location: yup.string().required("Required fields"),
    // property_owner: yup.string().required("Required fields"),
    // property_documents:yup.string().required("Required fields"),
    // 

    // Documents
    // adhar_front: yup.mixed().required("Aadhaar front image is Required"),
    // adhar_back: yup.mixed().required("Aadhaar Back image is required"),
    // pancard: yup.mixed().required("Pan Card is required"),
    // applicant_photo: yup.mixed().required("Applicant is required"),
    // address_proof: yup.mixed().required("Address Proof is required"),
    // first_month_salary: yup.mixed().required("First Month Salary is required"),
    // second_month_salary: yup.mixed().required("Second Month Salary is required"),
    // third_month_salary: yup.mixed().required("Third Month Salary is required"),
    // itr1: yup.string().required("ITR-1 is required"),
    // itr2: yup.string().required("ITR-2 is required"),

    // // other1:yup.string().required(""),
    // // other2:yup.string().required(""),
    // // other3:yup.string().required(""),
    // co_adhar_front:yup.string().required("Co-Applicant Aadhar is required"),
    // co_adhar_back:yup.string().required("Co-Applicant Aadhar is required"),
    // co_pancard:yup.string().required("Co-Applicant Pan Card is required"),
    // co_applicant_photo:yup.string().required("Co-Applicant Photo is required"),

})
export const GoldLoanValidation = yup.object().shape({
    fname: yup.string().required("Required field"),
    // mname: yup.string().notRequired("First Name is required"),
    lname: yup.string().required("Required field"),
    email: yup.string().email("Invalid Email").required("Required field"),
    phone: yup.string().required("Required field").matches(/^\d{10}$/, 'Phone number must be exactly 10 digits'),
    alternate_number: yup.string().required(" Required field").matches(/^\d{10}$/, 'Phone number must be exactly 10 digits'),
    dob: yup.string().required("Required field"),
    gender: yup.string().required("Required field"),
    marital_status: yup.string().required("Required field"),
    spouse_name: yup.string(),
    father_name: yup.string().required("Required field"),
    mother_name: yup.string().required("Required field"),
    house_name: yup.string().required("Required field"),
    street_name: yup.string().required("Required field"),
    city_name: yup.string().required("Required field"),
    landmark: yup.string().required("Required field"),
    district: yup.string().required("Required field"),
    state: yup.string().required("Required field"),
    pincode: yup.string().required("Required field"),
    present_house_name: yup.string().required("Required field"),
    present_street_name: yup.string().required("Required fields"),
    present_city_name: yup.string().required("Required fields"),
    present_landmark: yup.string().required("Required fields"),
    present_district: yup.string().required("Required fields"),
    present_state: yup.string().required("Required fields"),
    present_pincode: yup.string().required("Required fields"),
    //bank_details
    

})